#----------------------------------------
# configuration for creating DynamoDB table in the AWS cloud
# https://serverless.com/framework/docs/
#----------------------------------------
#
# edit ~/.aws/credentials with [serverless-admin] private keys
#
#    export AWS_PROFILE="serverless-admin"
#    export AWS_REGION=us-west-2
#    serverless deploy    # --aws-profile serverless-admin --region us-west-2
#
#
# This only needs to be run once to create the tables in the region desired.
#----------------------------------------

service: tournament-resources
frameworkVersion: '3'
configValidationMode: error


# Where the service will be deployed and what it can access
provider:
  name: aws
  region: us-west-2
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:*
          Resource: [
              "arn:aws:dynamodb:us-west-2:*:table/TS_*",
              "arn:aws:dynamodb:us-west-2:*:table/AtomicCounters"
          ]

# we need a secondary index on name to query all tournaments for a single archer
# format from "aws dynamodb describe-table --table-name TS_Archers"
resources:
  Resources:

    AtomicCountersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AtomicCounters
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH


    TournamentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TS_Tournaments
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: date
            AttributeType: S
          - AttributeName: code
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH

        GlobalSecondaryIndexes:
          - IndexName: tournamentDateCode-index
            KeySchema:
              - AttributeName: date
                KeyType: HASH
              - AttributeName: code
                KeyType: RANGE
            Projection:
              ProjectionType: ALL


    LeaguesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TS_Leagues
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N

        KeySchema:
          - AttributeName: id
            KeyType: HASH


    ArchersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TS_Archers
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: leagueId
            AttributeType: N
          - AttributeName: regionId
            AttributeType: N
          - AttributeName: tournamentId
            AttributeType: N
          - AttributeName: scoringGroup
            AttributeType: S
          - AttributeName: name
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH

        GlobalSecondaryIndexes:
          - IndexName: scoringGroup-index
            KeySchema:
              - AttributeName: tournamentId
                KeyType: HASH
              - AttributeName: scoringGroup
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

          - IndexName: nameAndTournament-index
            KeySchema:
              - AttributeName: name
                KeyType: HASH
              - AttributeName: tournamentId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

          - IndexName: league-index
            KeySchema:
              - AttributeName: leagueId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

          - IndexName: region-index
            KeySchema:
              - AttributeName: regionId
                KeyType: HASH
            Projection:
              ProjectionType: ALL


    RegionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TS_Regions
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N

        KeySchema:
          - AttributeName: id
            KeyType: HASH


    VenuesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TS_Venues
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N

        KeySchema:
          - AttributeName: id
            KeyType: HASH
